[versions]
agp = "7.3.0"
jitsiMeetSdk = "11.5.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.10.0"
activity = "1.8.0"
constraintlayout = "2.1.4"

kotlin = "1.7.20"
googleServices = "4.4.2"

reactNative = "0.77.2"
rtplibrary = "2.5.4"
iplayer = "2.1.26.1"
fragment = "1.3.6"

[libraries]
jitsi-meet-sdk = { module = "org.jitsi.react:jitsi-meet-sdk", version.ref = "jitsiMeetSdk" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

google-services = { module = "com.google.gms:google-services", version.ref = "googleServices" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
react-native = { module = "com.facebook.react:react-native", version.ref = "reactNative" }
rtplibrary = { module = "com.github.pedroSG94.rtmp-rtsp-stream-client-java:rtplibrary", version.ref = "rtplibrary" }

iplayer = { group = "com.github.hty527.iPlayer", name = "iplayer", version.ref = "iplayer" }

fragment = { group = "androidx.fragment", name = "fragment", version.ref = "fragment" }


[plugins]
kotlin-gradle = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
google-services-plugin = { id = "com.google.gms.google-services", version.ref = "googleServices" }

